### PR TITLE
chore: bump jest from 27 to 28

### PR DESCRIPTION
**Pull request by fargito**

### CODE REVIEW

**Review by adriencaccia — CHANGES_REQUESTED** [review]
Nice :clap: 
Great news that the tests are still passing!

Can you make the update in the examples too?

**Comment by fargito** [comment]
The upgrade is already made in the examples

**Comment by CorentinDoue** [comment]
If I understand correctly, the `uuid` package is not compatible with jest@28. 

I assume in swarmion/swarmion serverless-cdk-plugin is the only package to use `uuid`. Does it mean that all new projects created with Swarmion can't use `uuid` no more?

**Comment by fargito** [comment]
@CorentinDoue that is a good point, for now I guess `jest@28` and `uuid` are not compatible, see https://github.com/uuidjs/uuid/pull/616
For now I will close this issue then, and revert the upgrade in the starter

**Pull request closed without merging**
